name: tamizshahr
description: Appliction of Tamiz Shahr

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.2.2
  intl: ^0.19.0
  flutter_widget_from_html_core: ^0.15.2
  url_launcher: ^6.3.1
  html: ^0.15.5
  flutter_spinkit: ^5.2.1
  shamsi_date: ^1.0.4
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.10.0
  fluttertoast: ^8.2.8

  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  geolocator: ^10.1.0
  flutter_osm_plugin: ^0.70.4
  dartz: ^0.10.1
  loading_animation_widget: ^1.3.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.6.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobile_Bold.ttf
        - asset: assets/fonts/IRANSansMobile_Light.ttf
        - asset: assets/fonts/IRANSansMobile_UltraLight.ttf
          weight: 700
    - family: IransansNonEn
      fonts:
        - asset: assets/fonts/IRANSansMobileNoEnMedium.ttf
          weight: 700
    - family: BFarnaz
      fonts:
        - asset: assets/fonts/B_Farnaz.ttf
          weight: 700


